## Challenge 1
Use the pandas library to explore the provided dataset and answer the questions in the Google Form.

## Do's and Don'ts

Only use Pandas to gather information about this dataset. Do not load the data file with an external program like Excel or Google Sheet.

In [1]:
%%capture
!python3 -m pip install --upgrade pip setuptools wheel request
!pip3 install pandas sklearn matplotlib

In [2]:
import pandas as pd

In [3]:
train_dataset = pd.read_csv('data/train_dataset.csv')
train_dataset

,Age,Sex,HighChol,CholCheck,BMI,Smoker,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,GenHlth,MentHlth,PhysHlth,DiffWalk,Diabetes,Hypertension,Stroke
0,5.0,1.0,1.0,1.0,26.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,2.0,0.0,0.0,1.0,0.0,0.0
1,11.0,0.0,1.0,1.0,39.0,1.0,0.0,0.0,1.0,1.0,0.0,4.0,20.0,30.0,1.0,1.0,1.0,1.0
2,11.0,0.0,0.0,1.0,20.0,1.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
3,10.0,1.0,1.0,1.0,34.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,0.0,30.0,1.0,1.0,1.0,0.0
4,7.0,1.0,1.0,1.0,33.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58288,9.0,1.0,1.0,1.0,27.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,3.0,0.0,1.0,1.0,0.0
58289,8.0,1.0,0.0,1.0,27.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0
58290,9.0,1.0,0.0,1.0,36.0,1.0,0.0,1.0,0.0,0.0,0.0,4.0,0.0,30.0,1.0,1.0,1.0,0.0
58291,9.0,1.0,0.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
58292,9.0,0.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# write pandas code here to answer Part 1 questions
train_dataset.describe()

,Age,Sex,HighChol,CholCheck,BMI,Smoker,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,GenHlth,MentHlth,PhysHlth,DiffWalk,Diabetes,Hypertension,Stroke
count,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000,58293.000000
mean,8.606591,0.479269,0.534833,0.967217,30.221021,0.509341,0.153226,0.653389,0.567753,0.759011,0.045803,2.938243,4.020448,6.400820,0.282744,0.532928,0.565883,0.068893
std,2.857449,0.499574,0.498789,0.178069,7.577594,0.499917,0.360208,0.475895,0.495393,0.427688,0.209060,1.101764,8.330677,10.333056,0.450337,0.498919,0.495645,0.253275
min,1.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.000000,0.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,9.000000,0.000000,1.000000,1.000000,29.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
75%,11.000000,1.000000,1.000000,1.000000,34.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,7.000000,1.000000,1.000000,1.000000,0.000000
max,13.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,1.000000,1.000000

## Challenge 2

Now that we have some familiarity with this dataset, we'll train a simple [logistic regression](https://www.youtube.com/watch?v=yIYKR4sgzI8) model using the Scikit-learn library. Your main task is to generate evaluation metrics to assess the model's performance, while the code for training the logistic model has been provided for you.

In [ ]:
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, roc_auc_score

In [ ]:
model = LogisticRegression()

In [ ]:
test_dataset = pd.read_csv('data/test_dataset.csv')

In [ ]:
train_X = train_dataset[['BMI', 'GenHlth', 'Age']]
train_Y = train_dataset[['Diabetes']].values.reshape(-1)

In [ ]:
model.fit(train_X, train_Y)

In [ ]:
# write code here to answer questions for Part 2

## Challenge 3

Solve the following question just using python:

- Total number of words. Strings like `a.k.a` and `e.g.` should be considered a single word
- Total number of unique words. `"spam"` and `spam` should be considered the same word
- What is the most frequent word that appears in the below text (case insenstive)? Exclude stop words (e.g `and`, `or`, `the`). A list of stop words have been provided.

## Do's and Don'ts

Do not download (`pip install`) any external libs to solve this problem. Just use python and any built-in modules you may need.

In [ ]:
# source: https://sites.astro.caltech.edu/~george/ay122/cacm12.pdf
TEXT = '''
Machine learning systems automatically learn programs from
data. This is often a very attractive alternative to manually
constructing them, and in the last decade the use of machine
learning has spread rapidly throughout computer science
and beyond. Machine learning is used in Web search, spam
filters, recommender systems, ad placement, credit scoring,
fraud detection, stock trading, drug design, and many other
applications. A recent report from the McKinsey Global Institute asserts that machine learning (a.k.a. data mining or
predictive analytics) will be the driver of the next big wave of
innovation [15]. Several fine textbooks are available to interested practitioners and researchers (e.g, [16, 24]). However,
much of the “folk knowledge” that is needed to successfully
develop machine learning applications is not readily available in them. As a result, many machine learning projects
take much longer than necessary or wind up producing lessthan-ideal results. Yet much of this folk knowledge is fairly
easy to communicate. This is the purpose of this article.
Many different types of machine learning exist, but for illustration purposes I will focus on the most mature and
widely used one: classification. Nevertheless, the issues I
will discuss apply across all of machine learning. A classifier is a system that inputs (typically) a vector of discrete
and/or continuous feature values and outputs a single discrete value, the class. For example, a spam filter classifies
email messages into “spam” or “not spam,” and its input may
be a Boolean vector x = (x1, . . . , xj , . . . , xd), where xj = 1
if the jth word in the dictionary appears in the email and
xj = 0 otherwise. A learner inputs a training set of examples (xi, yi), where xi = (xi,1, . . . , xi,d) is an observed input
and yi is the corresponding output, and outputs a classifier.
The test of the learner is whether this classifier produces the
correct output yt for future examples xt (e.g., whether the
spam filter correctly classifies previously unseen emails as
spam or not spam).
'''

STOP_WORDS = ['a', 'an', 'the', 'in', 'on', 'at', 'for', 'is', 'it', 'and', 'or', 'but', 'with', 'of', 'to']

In [ ]:
# Write your code here